In [90]:
# !pip install xformers pandas

In [91]:
from xformers.ops.fmha.attn_bias import (
    AttentionBias,
    BlockDiagonalCausalMask,
    BlockDiagonalCausalWithOffsetPaddedKeysMask,
    BlockDiagonalMask,
)

import pandas as pd

In [92]:
col_dict = {0.0: '#68A357', float('-inf'): '#C97064'}
def colour_cell(val):
    if val in col_dict:
        return 'Background-color: %s' % col_dict[val]
    return ''

In [93]:
## BlockDiagonalCausalMask

seqlens = [7, 5, 6]
sliding_window_size = 3

mask = BlockDiagonalCausalMask.from_seqlens(seqlens).make_local_attention(sliding_window_size)

batch_size = 1
total_seq_len = sum(seqlens)
mask_tensor = mask.materialize((batch_size, total_seq_len, total_seq_len))

df = pd.DataFrame(mask_tensor[0, :, :].numpy())
df.style.applymap(colour_cell)

/tmp/ipykernel_9898/2484427568.py:13: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(colour_cell)

In [94]:
## BlockDiagonalMask

q_seqlens = [3, 5]
kv_seqlens = [10, 8] # (3 + 7, 5 + 3)
sliding_window_size = 3

mask = BlockDiagonalMask.from_seqlens(q_seqlens, kv_seqlens).make_local_attention_from_bottomright(sliding_window_size)

batch_size = 1
total_seq_len = sum(q_seqlens)
total_kv_seq_len = sum(kv_seqlens)
mask_tensor = mask.materialize((batch_size, total_seq_len, total_kv_seq_len))

df = pd.DataFrame(mask_tensor[0, :, :].numpy())
df.style.applymap(colour_cell)

/tmp/ipykernel_9898/1506970582.py:15: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(colour_cell)

In [95]:
## BlockDiagonalCausalWithOffsetPaddedKeysMask

q_seqlen = [1, 1]
kv_seq_len = [3, 5]
kv_padding = 6

mask = BlockDiagonalCausalWithOffsetPaddedKeysMask.from_seqlens(q_seqlen=q_seqlen, kv_padding=kv_padding, kv_seqlen=kv_seq_len)

batch_size = 1
total_seq_len = sum(q_seqlen)
total_kv_seq_len = kv_padding * len(kv_seq_len)

mask_tensor = mask.materialize((batch_size, total_seq_len, total_kv_seq_len))

df = pd.DataFrame(mask_tensor[0, :, :].numpy())
df.style.applymap(colour_cell)

/tmp/ipykernel_9898/2637469656.py:16: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(colour_cell)